module.exprots = {
    Confirm: require('../components/g-confirm'),
    Copyright: require('../components/g-copyright'),
    FooterNav: require('../components/g-footer-nav'),
    GoTop: require('../components/g-go-top'),
    JumpLink: require('../components/g-jump-link'),
    LazyLoad: require('../components/g-lazy-load'),
    Loading: require('../components/g-loading'),
    Mask: require('../components/g-mask'),
    Message: require('../components/g-message'),
    Navigation: require('../components/g-navigation'),
    NoData: require('../components/g-no-data'),
    Pagination: require('../components/g-pagination'),
    Popover: require('../components/g-popover'), // 待修改...
    ProgressBar: require('../components/g-progress-bar'),
    RadioSwitch: require('../components/g-radio-switch'),
    SortTab: require('../components/g-sort-tab'),
    Star: require('../components/g-star'),
    Sub: require('../components/g-sub'),
    SubEs6: require('../components/g-sub-es6'),
    Table: require('../components/g-table'),
    Tooltip: require('../components/g-tooltip'),
    TooltipApp: require('../components/g-tooltip-app'), // 待修改...
    Validate: require('../components/g-validate'),
};
