module.exports = {
    Confirm: require('../components_jq/g-confirm'),
    Copyright: require('../components_jq/g-copyright'),
    FooterNav: require('../components_jq/g-footer-nav'),
    GoTop: require('../components_jq/g-go-top'),
    JumpLink: require('../components_jq/g-jump-link'),
    LazyLoad: require('../components_jq/g-lazy-load'),
    Loading: require('../components_jq/g-loading'),
    Mask: require('../components_jq/g-mask'),
    Message: require('../components_jq/g-message'),
    Navigation: require('../components_jq/g-navigation'),
    NoData: require('../components_jq/g-no-data'),
    Pagination: require('../components_jq/g-pagination'),
    Popover: require('../components_jq/g-popover'),
    ProgressBar: require('../components_jq/g-progress-bar'),
    RadioSwitch: require('../components_jq/g-radio-switch'),
    SortTab: require('../components_jq/g-sort-tab'),
    Star: require('../components_jq/g-star'),
    Sub: require('../components_jq/g-sub'),
    Table: require('../components_jq/g-table'),
    Tooltip: require('../components_jq/g-tooltip'),
    TooltipApp: require('../components_jq/g-tooltip-app'),
    Validate: require('../components_jq/g-validate'),
};
